# -*- coding: utf-8 -*-
"""RectFlowMNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUIIyaY-5bDzI_foS2Ye0eLAWmATYV0y

# **Minimal MNIST Rectified Flow Notebook with Reflow, and One-Step Distillation**

This notebook implements a **minimal unconditional MNIST** version of the Rectified Flow pipeline. It starts with a standard CFM teacher, performs **reflow** to obtain a **2-Rectified Flow**, optionally repeats reflow for **\(k=3\)**, and then adds the paper’s **one-step distillation** stage after \(k=2\) and optionally after \(k=3\).

Along the way, the notebook tracks three flow-side metrics:

1. the **straightness measure**,
2. the extra **endpoint-consistency** metric,
3. the **quadratic transport cost** \(\mathbb{E}\|Z_1-Z_0\|^2\), which is a special case of the paper’s non-increasing convex transport cost viewpoint.

For distillation, the notebook then tracks the separate **one-step endpoint MSE** against the source flow’s endpoints.

**Block 1 — Imports and Global Configuration**

This cell imports the required libraries, sets the random seed, chooses the device, and defines the main hyperparameters used throughout the notebook.

For A100 run, the default schedule in this version is **50 CFM epochs**, **20 reflow epochs**, and **12 distillation epochs**. The notebook also smooths the metric curves and evaluates them on larger Monte Carlo batches so the plots are less noisy.
"""

# Block 1: Imports and global config

import copy
import json
import math
import random
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
import torchvision.transforms as transforms
from torchvision.utils import make_grid, save_image
from tqdm.auto import tqdm

# -----------------------------
# User config
# -----------------------------
SEED = 1234
DATA_ROOT = "./datasets"
OUT_DIR = Path("./mnist_rectified_flow_notebook_runs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

BATCH_SIZE = 128
HIDDEN_DIM = 128
N_LAYERS = 6
LR = 1e-4

CFM_EPOCHS = 50
REFLOW_EPOCHS = 20
DISTILL_EPOCHS = 12   # final one-step distillation after a rectified flow

PAIR_STEPS = 32          # teacher solver steps used to generate reflow pairs
PAIR_SOLVER = "midpoint" # better for teacher pair generation
SAMPLE_SOLVER = "euler"  # used for low-NFE sample sweeps
SAMPLE_STEPS = [1, 2, 4, 8, 16]

VIS_N = 64
EVAL_BATCH_SIZE = 256

RUN_OPTIONAL_K3 = True   # pushed to the end of the notebook

# Checkpoint-tracking config for metric curves
TRACK_METRICS = True
TRACK_METRIC_EVERY = 2
TRACK_STRAIGHTNESS_BATCHES = 6
TRACK_ENDPOINT_BATCHES = 4
TRACK_ENDPOINT_STEPS = 16
FINAL_METRIC_BATCHES = 10
HISTORY_SMOOTHING_WINDOW = 3
SAVE_EPOCH_CHECKPOINTS = True

NUM_WORKERS = 0
SHOW_SAVED_SAMPLE_GRIDS = True
INLINE_SAMPLE_STEPS = [1, 2, 4, 16]

SHOW_TQDM = True
TQDM_UPDATE_EVERY = 20

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

"""**Block 2 — MNIST Data Loader**

This cell downloads MNIST, applies the minimal preprocessing needed for unconditional generation, and builds the training dataloader. The rest of the notebook assumes images are normalized into the same tensor format returned here.
"""

# Block 2: Data loader

def build_mnist_loader(data_root: str, batch_size: int, device: torch.device) -> DataLoader:
    transform = transforms.Compose([transforms.ToTensor()])
    dataset = MNIST(data_root, train=True, download=True, transform=transform)
    kwargs = {"num_workers": NUM_WORKERS, "pin_memory": device.type == "cuda"}
    return DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True, **kwargs)

train_loader = build_mnist_loader(DATA_ROOT, BATCH_SIZE, device)
print("Number of batches per epoch:", len(train_loader))
print("NUM_WORKERS =", NUM_WORKERS)

"""**Block 3 — Velocity Model for MNIST**

This cell defines the convolutional velocity network used to parameterize the flow on images. It is kept close to the original MNIST notebook so that the main new ingredient in this notebook is the rectification procedure, not a major model redesign.
"""

# Block 3: Model (kept close to the MNIST notebook)

class ConvBlock(nn.Conv2d):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        activation_fn: bool = False,
        stride: int = 1,
        padding: str | int = "same",
        dilation: int = 1,
        groups: int = 1,
        bias: bool = True,
        gn: bool = False,
        gn_groups: int = 8,
    ):
        if padding == "same":
            padding = (kernel_size // 2) * dilation
        super().__init__(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=groups,
            bias=bias,
        )
        self.activation_fn = nn.SiLU() if activation_fn else None
        self.group_norm = nn.GroupNorm(gn_groups, out_channels) if gn else None

    def forward(self, x: torch.Tensor, time_embedding: torch.Tensor | None = None, residual: bool = False):
        if residual:
            if time_embedding is None:
                raise ValueError("time_embedding is required when residual=True")
            x = x + time_embedding
            y = x
            x = super().forward(x)
            y = y + x
        else:
            y = super().forward(x)

        if self.group_norm is not None:
            y = self.group_norm(y)
        if self.activation_fn is not None:
            y = self.activation_fn(y)
        return y


class ImageFlow(nn.Module):
    def __init__(self, image_resolution=(28, 28, 1), hidden_dims=(128,) * 6):
        super().__init__()
        _, _, img_c = image_resolution
        hidden_dims = list(hidden_dims)
        if len(hidden_dims) < 2:
            raise ValueError("Need at least two hidden dimensions.")

        self.in_project = ConvBlock(img_c, hidden_dims[0], kernel_size=7)
        self.time_project = nn.Sequential(
            ConvBlock(1, hidden_dims[0], kernel_size=1, activation_fn=True),
            ConvBlock(hidden_dims[0], hidden_dims[1], kernel_size=1),
        )

        self.convs = nn.ModuleList([ConvBlock(hidden_dims[0], hidden_dims[0], kernel_size=3)])
        for idx in range(1, len(hidden_dims)):
            dilation = 3 ** ((idx - 1) // 2)
            self.convs.append(
                ConvBlock(
                    hidden_dims[idx - 1],
                    hidden_dims[idx],
                    kernel_size=3,
                    dilation=dilation,
                    activation_fn=True,
                    gn=True,
                    gn_groups=8,
                )
            )

        self.out_project = ConvBlock(hidden_dims[-1], img_c, kernel_size=3)

    @staticmethod
    def interpolate(x0: torch.Tensor, x1: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        return (1.0 - t) * x0 + t * x1

    @staticmethod
    def target_velocity(x0: torch.Tensor, x1: torch.Tensor) -> torch.Tensor:
        return x1 - x0

    def forward(self, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        if t.ndim == 1:
            t = t[:, None, None, None]
        elif t.ndim == 2:
            t = t[:, :, None, None]

        time_embedding = self.time_project(t)
        y = self.in_project(x)
        for block in self.convs:
            y = block(y, time_embedding, residual=True)
        return self.out_project(y)


def count_parameters(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

hidden_dims = [HIDDEN_DIM for _ in range(N_LAYERS)]
teacher = ImageFlow(image_resolution=(28, 28, 1), hidden_dims=hidden_dims).to(device)
print("Trainable parameters:", f"{count_parameters(teacher):,}")

"""**Block 4 — ODE Integration and Sampling Helpers**

This cell defines the numerical integrator used to evolve samples from noise to data. These helpers are reused both for generating samples at different NFEs and for constructing teacher-generated endpoint pairs during reflow.
"""

# Block 4: ODE integration and sampling helpers

@torch.no_grad()
def integrate_flow(
    model: nn.Module,
    x0: torch.Tensor,
    num_steps: int,
    solver: str = "euler",
    return_path: bool = False,
):
    if num_steps < 1:
        raise ValueError("num_steps must be >= 1")

    model.eval()
    x = x0.clone()
    if return_path:
        path = [x.clone()]

    if num_steps == 1:
        t0 = torch.zeros(x.shape[0], 1, 1, 1, device=x.device, dtype=x.dtype)
        x = x + model(x, t0)
        if return_path:
            path.append(x.clone())
            return torch.stack(path, dim=0)
        return x

    dt = 1.0 / num_steps
    t_scalar = 0.0
    for _ in range(num_steps):
        if solver == "euler":
            t = torch.full((x.shape[0], 1, 1, 1), t_scalar, device=x.device, dtype=x.dtype)
            v = model(x, t)
            x = x + dt * v
        elif solver == "midpoint":
            t = torch.full((x.shape[0], 1, 1, 1), t_scalar, device=x.device, dtype=x.dtype)
            v1 = model(x, t)
            x_mid = x + 0.5 * dt * v1
            t_mid = torch.full((x.shape[0], 1, 1, 1), t_scalar + 0.5 * dt, device=x.device, dtype=x.dtype)
            v2 = model(x_mid, t_mid)
            x = x + dt * v2
        else:
            raise ValueError("solver must be 'euler' or 'midpoint'")

        t_scalar += dt
        if return_path:
            path.append(x.clone())

    if return_path:
        return torch.stack(path, dim=0)
    return x


@torch.no_grad()
def sample_images(
    model: nn.Module,
    n_samples: int,
    batch_size: int,
    num_steps: int,
    device: torch.device,
    solver: str = "euler",
):
    outs = []
    remaining = n_samples
    while remaining > 0:
        cur = min(batch_size, remaining)
        x0 = torch.randn(cur, 1, 28, 28, device=device)
        x1 = integrate_flow(model, x0, num_steps=num_steps, solver=solver, return_path=False)
        outs.append(x1.cpu())
        remaining -= cur
    return torch.cat(outs, dim=0)


@torch.no_grad()
def save_sample_grid(
    samples: torch.Tensor,
    out_path: Path,
    nrow: int = 8,
    show_inline: bool = False,
    title: str | None = None,
):
    grid = make_grid(samples.clamp(0, 1), nrow=nrow)
    save_image(grid, out_path)
    print("Saved:", out_path)
    if show_inline:
        grid_np = grid.detach().cpu().numpy()
        grid_np = np.transpose(grid_np, (1, 2, 0))
        plt.figure(figsize=(6, 6))
        if grid_np.shape[-1] == 1:
            plt.imshow(grid_np[..., 0], cmap="gray")
        else:
            plt.imshow(grid_np)
        if title is not None:
            plt.title(title)
        plt.axis("off")
        plt.tight_layout()
        plt.show()

"""**Block 5 — Training Batch Construction**

This cell defines how training triples are built for the two stages. For stage 1, it uses the standard CFM interpolation between Gaussian noise and real MNIST images; for reflow, it builds new pairs from trajectories generated by the previous model.
"""

# Block 5: Training batch samplers

def sample_cfm_training_batch(x1: torch.Tensor):
    x0 = torch.randn_like(x1)
    t = torch.rand(x1.shape[0], 1, 1, 1, device=x1.device, dtype=x1.dtype)
    x_t = ImageFlow.interpolate(x0, x1, t)
    target = ImageFlow.target_velocity(x0, x1)
    return x_t, t, target


@torch.no_grad()
def sample_reflow_training_batch(
    teacher: nn.Module,
    batch_size: int,
    device: torch.device,
    pair_steps: int,
    pair_solver: str,
):
    x0 = torch.randn(batch_size, 1, 28, 28, device=device)
    x1 = integrate_flow(teacher, x0, num_steps=pair_steps, solver=pair_solver, return_path=False)
    t = torch.rand(batch_size, 1, 1, 1, device=device)
    x_t = ImageFlow.interpolate(x0, x1, t)
    target = ImageFlow.target_velocity(x0, x1)
    return x_t, t, target

"""**Block 5A — Metric Helpers**

This cell defines the three evaluation metrics used later in the notebook.

- The first is the **straightness measure**.
- The second is the **endpoint-consistency** measure
- The third is the **quadratic transport cost** \(\mathbb{E}\|Z_1-Z_0\|^2\), included as a special case of the paper’s convex transport-cost perspective.

To reduce Monte Carlo noise, the endpoint-consistency metric is averaged across multiple independent trajectory batches, and the checkpoint curves later use a small moving-average smoother for visualization.
"""

# Block 5A: Metric helpers (defined early so training can track checkpoints)

@torch.no_grad()
def estimate_paper_straightness(
    model: nn.Module,
    device: torch.device,
    batch_size: int = 128,
    pair_steps: int = 32,
    pair_solver: str = "midpoint",
    batches: int = 8,
):
    model.eval()
    vals = []
    for _ in range(batches):
        x0 = torch.randn(batch_size, 1, 28, 28, device=device)
        x1 = integrate_flow(model, x0, num_steps=pair_steps, solver=pair_solver, return_path=False)
        t = torch.rand(batch_size, 1, 1, 1, device=device)
        x_t = ImageFlow.interpolate(x0, x1, t)
        chord = x1 - x0
        pred = model(x_t, t)
        vals.append(F.mse_loss(pred, chord).item())
    return float(np.mean(vals))


@torch.no_grad()
def estimate_endpoint_consistency(
    model: nn.Module,
    device: torch.device,
    batch_size: int = 64,
    num_steps: int = 16,
    solver: str = "euler",
    batches: int = 4,
):
    model.eval()
    batch_vals = []
    for _ in range(batches):
        x0 = torch.randn(batch_size, 1, 28, 28, device=device)
        path = integrate_flow(model, x0, num_steps=num_steps, solver=solver, return_path=True)
        z1 = path[-1]
        errs = []

        for i in range(num_steps):
            t_scalar = i / num_steps
            zt = path[i]
            t = torch.full((batch_size, 1, 1, 1), t_scalar, device=device)
            vt = model(zt, t)
            z1_hat = zt + (1.0 - t_scalar) * vt
            errs.append(F.mse_loss(z1_hat, z1).item())

        batch_vals.append(float(np.mean(errs)))
    return float(np.mean(batch_vals))


@torch.no_grad()
def estimate_quadratic_transport_cost(
    model: nn.Module,
    device: torch.device,
    batch_size: int = 128,
    pair_steps: int = 32,
    pair_solver: str = "midpoint",
    batches: int = 8,
):
    model.eval()
    vals = []
    for _ in range(batches):
        x0 = torch.randn(batch_size, 1, 28, 28, device=device)
        x1 = integrate_flow(model, x0, num_steps=pair_steps, solver=pair_solver, return_path=False)
        disp = (x1 - x0).flatten(1)
        vals.append((disp.pow(2).sum(dim=1).mean()).item())
    return float(np.mean(vals))


@torch.no_grad()
def evaluate_metric_bundle(
    model: nn.Module,
    device: torch.device,
    straightness_batch_size: int = 128,
    straightness_pair_steps: int = 32,
    straightness_pair_solver: str = "midpoint",
    straightness_batches: int = 4,
    endpoint_batch_size: int = 128,
    endpoint_steps: int = 16,
    endpoint_solver: str = "euler",
    endpoint_batches: int = 2,
    transport_batch_size: int = 128,
    transport_pair_steps: int = 32,
    transport_pair_solver: str = "midpoint",
    transport_batches: int = 4,
):
    return {
        "paper_straightness": estimate_paper_straightness(
            model,
            device=device,
            batch_size=straightness_batch_size,
            pair_steps=straightness_pair_steps,
            pair_solver=straightness_pair_solver,
            batches=straightness_batches,
        ),
        "endpoint_consistency": estimate_endpoint_consistency(
            model,
            device=device,
            batch_size=endpoint_batch_size,
            num_steps=endpoint_steps,
            solver=endpoint_solver,
            batches=endpoint_batches,
        ),
        "quadratic_transport_cost": estimate_quadratic_transport_cost(
            model,
            device=device,
            batch_size=transport_batch_size,
            pair_steps=transport_pair_steps,
            pair_solver=transport_pair_solver,
            batches=transport_batches,
        ),
    }

"""**Block 6 — Training Functions**

This cell contains the training loops for the stage-1 CFM model and the later reflow stages. It also supports checkpoint-wise metric tracking so we can plot straightness and endpoint-consistency over training.
"""

# Block 6: Training functions

def maybe_tqdm(iterable, enabled: bool = True, **kwargs):
    return tqdm(iterable, **kwargs) if enabled else iterable


def train_cfm_stage(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    epochs: int,
    lr: float,
    stage_name: str = "stage1_cfm",
    track_metrics: bool = True,
    track_metric_every: int = 1,
    track_straightness_batches: int = 6,
    track_endpoint_batches: int = 4,
    track_endpoint_steps: int = 16,
    checkpoint_dir: Path | None = None,
):
    optimizer = AdamW(model.parameters(), lr=lr, betas=(0.9, 0.99))
    losses = []
    history = []
    model.train()

    if checkpoint_dir is not None:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

    for epoch in range(epochs):
        running = 0.0
        count = 0
        batch_iter = maybe_tqdm(
            loader,
            enabled=SHOW_TQDM,
            desc=f"{stage_name} | epoch {epoch + 1}/{epochs}",
            leave=False,
            dynamic_ncols=True,
        )
        for batch_idx, (x1, _) in enumerate(batch_iter, start=1):
            x1 = x1.to(device)
            x_t, t, target = sample_cfm_training_batch(x1)

            optimizer.zero_grad(set_to_none=True)
            pred = model(x_t, t)
            loss = F.mse_loss(pred, target)
            loss.backward()
            optimizer.step()

            losses.append(loss.item())
            running += loss.item()
            count += 1

            if SHOW_TQDM and hasattr(batch_iter, "set_postfix") and (
                batch_idx % TQDM_UPDATE_EVERY == 0 or batch_idx == len(loader)
            ):
                batch_iter.set_postfix(batch_loss=f"{loss.item():.4f}", avg_loss=f"{running / count:.4f}")

        avg = running / max(1, count)
        entry = {"epoch": epoch + 1, "avg_loss": float(avg)}

        should_track = track_metrics and (((epoch + 1) % track_metric_every == 0) or (epoch + 1 == epochs))
        if should_track:
            metrics = evaluate_metric_bundle(
                model,
                device=device,
                straightness_batch_size=EVAL_BATCH_SIZE,
                straightness_pair_steps=PAIR_STEPS,
                straightness_pair_solver=PAIR_SOLVER,
                straightness_batches=track_straightness_batches,
                endpoint_batch_size=EVAL_BATCH_SIZE,
                endpoint_steps=track_endpoint_steps,
                endpoint_solver=SAMPLE_SOLVER,
                endpoint_batches=track_endpoint_batches,
                transport_batch_size=EVAL_BATCH_SIZE,
                transport_pair_steps=PAIR_STEPS,
                transport_pair_solver=PAIR_SOLVER,
                transport_batches=max(1, track_straightness_batches),
            )
            entry.update(metrics)
            print(
                f"[{stage_name}] epoch {epoch + 1}/{epochs} - loss: {avg:.6f} | "
                f"straightness: {metrics['paper_straightness']:.6f} | "
                f"endpoint_consistency: {metrics['endpoint_consistency']:.6f} | "
                f"quadratic_transport_cost: {metrics['quadratic_transport_cost']:.6f}"
            )
        else:
            print(f"[{stage_name}] epoch {epoch + 1}/{epochs} - loss: {avg:.6f}")

        history.append(entry)

        if checkpoint_dir is not None:
            torch.save(
                {
                    "model": model.state_dict(),
                    "losses": losses,
                    "history": history,
                    "epoch": epoch + 1,
                    "stage_name": stage_name,
                },
                checkpoint_dir / f"{stage_name}_epoch_{epoch + 1:02d}.pt",
            )

    return model, losses, history


def train_reflow_stage(
    teacher: nn.Module,
    loader: DataLoader,
    device: torch.device,
    epochs: int,
    lr: float,
    stage_name: str,
    pair_steps: int,
    pair_solver: str,
    track_metrics: bool = True,
    track_metric_every: int = 1,
    track_straightness_batches: int = 6,
    track_endpoint_batches: int = 4,
    track_endpoint_steps: int = 16,
    checkpoint_dir: Path | None = None,
):
    student = copy.deepcopy(teacher).to(device)
    teacher.eval()
    student.train()

    optimizer = AdamW(student.parameters(), lr=lr, betas=(0.9, 0.99))
    losses = []
    history = []

    if checkpoint_dir is not None:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

    batch_size = loader.batch_size or 128
    for epoch in range(epochs):
        running = 0.0
        count = 0
        batch_iter = maybe_tqdm(
            loader,
            enabled=SHOW_TQDM,
            desc=f"{stage_name} | epoch {epoch + 1}/{epochs}",
            leave=False,
            dynamic_ncols=True,
        )
        for batch_idx, (_x, _) in enumerate(batch_iter, start=1):
            x_t, t, target = sample_reflow_training_batch(
                teacher=teacher,
                batch_size=batch_size,
                device=device,
                pair_steps=pair_steps,
                pair_solver=pair_solver,
            )

            optimizer.zero_grad(set_to_none=True)
            pred = student(x_t, t)
            loss = F.mse_loss(pred, target)
            loss.backward()
            optimizer.step()

            losses.append(loss.item())
            running += loss.item()
            count += 1

            if SHOW_TQDM and hasattr(batch_iter, "set_postfix") and (
                batch_idx % TQDM_UPDATE_EVERY == 0 or batch_idx == len(loader)
            ):
                batch_iter.set_postfix(batch_loss=f"{loss.item():.4f}", avg_loss=f"{running / count:.4f}")

        avg = running / max(1, count)
        entry = {"epoch": epoch + 1, "avg_loss": float(avg)}

        should_track = track_metrics and (((epoch + 1) % track_metric_every == 0) or (epoch + 1 == epochs))
        if should_track:
            metrics = evaluate_metric_bundle(
                student,
                device=device,
                straightness_batch_size=EVAL_BATCH_SIZE,
                straightness_pair_steps=PAIR_STEPS,
                straightness_pair_solver=PAIR_SOLVER,
                straightness_batches=track_straightness_batches,
                endpoint_batch_size=EVAL_BATCH_SIZE,
                endpoint_steps=track_endpoint_steps,
                endpoint_solver=SAMPLE_SOLVER,
                endpoint_batches=track_endpoint_batches,
            )
            entry.update(metrics)
            print(
                f"[{stage_name}] epoch {epoch + 1}/{epochs} - loss: {avg:.6f} | "
                f"straightness: {metrics['paper_straightness']:.6f} | "
                f"endpoint_consistency: {metrics['endpoint_consistency']:.6f} | "
                f"quadratic_transport_cost: {metrics['quadratic_transport_cost']:.6f}"
            )
        else:
            print(f"[{stage_name}] epoch {epoch + 1}/{epochs} - loss: {avg:.6f}")

        history.append(entry)

        if checkpoint_dir is not None:
            torch.save(
                {
                    "model": student.state_dict(),
                    "losses": losses,
                    "history": history,
                    "epoch": epoch + 1,
                    "stage_name": stage_name,
                },
                checkpoint_dir / f"{stage_name}_epoch_{epoch + 1:02d}.pt",
            )

    return student, losses, history

"""**Block 6A — One-Step Distillation Helpers**

These helpers implement the paper’s **final one-step distillation idea**.

After we obtain a \(k\)-rectified flow, we can train a direct one-step predictor
\[
\hat T(z_0)=z_0+v_	heta(z_0,0)
\]
to map the starting noise \(z_0\) directly to the final endpoint \(Z_1^k\).

For this section, the right metric is **one-step endpoint MSE**, because the distilled model no longer defines a full trajectory.  
The **straightness metric still belongs to the source rectified flow**, and it explains why this one-step approximation becomes easier after rectification.

"""

# Block 6A: One-step distillation helpers

@torch.no_grad()
def one_step_predict(model: nn.Module, x0: torch.Tensor) -> torch.Tensor:
    model.eval()
    t0 = torch.zeros(x0.shape[0], 1, 1, 1, device=x0.device, dtype=x0.dtype)
    return x0 + model(x0, t0)


@torch.no_grad()
def sample_images_one_step(
    model: nn.Module,
    n_samples: int,
    batch_size: int,
    device: torch.device,
):
    outs = []
    remaining = n_samples
    while remaining > 0:
        cur = min(batch_size, remaining)
        x0 = torch.randn(cur, 1, 28, 28, device=device)
        x1_hat = one_step_predict(model, x0)
        outs.append(x1_hat.cpu())
        remaining -= cur
    return torch.cat(outs, dim=0)


@torch.no_grad()
def estimate_t0_endpoint_consistency(
    flow_model: nn.Module,
    device: torch.device,
    batch_size: int = 128,
    pair_steps: int = 32,
    pair_solver: str = "midpoint",
    batches: int = 8,
):
    flow_model.eval()
    vals = []
    for _ in range(batches):
        x0 = torch.randn(batch_size, 1, 28, 28, device=device)
        z1 = integrate_flow(flow_model, x0, num_steps=pair_steps, solver=pair_solver, return_path=False)
        z1_hat = one_step_predict(flow_model, x0)
        vals.append(F.mse_loss(z1_hat, z1).item())
    return float(np.mean(vals))


@torch.no_grad()
def estimate_distilled_one_step_mse(
    distilled_model: nn.Module,
    source_flow: nn.Module,
    device: torch.device,
    batch_size: int = 128,
    pair_steps: int = 32,
    pair_solver: str = "midpoint",
    batches: int = 8,
):
    distilled_model.eval()
    source_flow.eval()
    vals = []
    for _ in range(batches):
        x0 = torch.randn(batch_size, 1, 28, 28, device=device)
        z1 = integrate_flow(source_flow, x0, num_steps=pair_steps, solver=pair_solver, return_path=False)
        z1_hat = one_step_predict(distilled_model, x0)
        vals.append(F.mse_loss(z1_hat, z1).item())
    return float(np.mean(vals))


def train_distillation_stage(
    source_flow: nn.Module,
    loader: DataLoader,
    device: torch.device,
    epochs: int,
    lr: float,
    stage_name: str,
    pair_steps: int,
    pair_solver: str,
    track_metrics: bool = True,
    track_metric_every: int = 1,
    checkpoint_dir: Path | None = None,
):
    student = copy.deepcopy(source_flow).to(device)
    source_flow.eval()
    student.train()

    optimizer = AdamW(student.parameters(), lr=lr, betas=(0.9, 0.99))
    losses = []
    history = []

    if checkpoint_dir is not None:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

    batch_size = loader.batch_size or 128
    for epoch in range(epochs):
        running = 0.0
        count = 0
        batch_iter = maybe_tqdm(
            loader,
            enabled=SHOW_TQDM,
            desc=f"{stage_name} | epoch {epoch + 1}/{epochs}",
            leave=False,
            dynamic_ncols=True,
        )
        for batch_idx, (_x, _) in enumerate(batch_iter, start=1):
            x0 = torch.randn(batch_size, 1, 28, 28, device=device)
            with torch.no_grad():
                z1 = integrate_flow(source_flow, x0, num_steps=pair_steps, solver=pair_solver, return_path=False)

            t0 = torch.zeros(batch_size, 1, 1, 1, device=device)
            target_disp = z1 - x0

            optimizer.zero_grad(set_to_none=True)
            pred_disp = student(x0, t0)
            loss = F.mse_loss(pred_disp, target_disp)
            loss.backward()
            optimizer.step()

            losses.append(loss.item())
            running += loss.item()
            count += 1

            if SHOW_TQDM and hasattr(batch_iter, "set_postfix") and (
                batch_idx % TQDM_UPDATE_EVERY == 0 or batch_idx == len(loader)
            ):
                batch_iter.set_postfix(batch_loss=f"{loss.item():.4f}", avg_loss=f"{running / count:.4f}")

        avg = running / max(1, count)
        entry = {"epoch": epoch + 1, "avg_loss": float(avg)}

        should_track = track_metrics and (((epoch + 1) % track_metric_every == 0) or (epoch + 1 == epochs))
        if should_track:
            one_step_mse = estimate_distilled_one_step_mse(
                distilled_model=student,
                source_flow=source_flow,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=max(2, TRACK_STRAIGHTNESS_BATCHES),
            )
            entry["one_step_endpoint_mse"] = one_step_mse
            print(
                f"[{stage_name}] epoch {epoch + 1}/{epochs} - loss: {avg:.6f} | "
                f"one_step_endpoint_mse: {one_step_mse:.6f}"
            )
        else:
            print(f"[{stage_name}] epoch {epoch + 1}/{epochs} - loss: {avg:.6f}")

        history.append(entry)

        if checkpoint_dir is not None:
            torch.save(
                {
                    "model": student.state_dict(),
                    "losses": losses,
                    "history": history,
                    "epoch": epoch + 1,
                    "stage_name": stage_name,
                },
                checkpoint_dir / f"{stage_name}_epoch_{epoch + 1:02d}.pt",
            )

    return student, losses, history

"""## **Main Experiments: Stage 1 and Stage 2**

1. **sample grids across NFEs**,
2. **straightness**,
3. **endpoint-consistency**,
4. **quadratic transport cost**,
5. **one-step distillation** after \(k=2\).

The optional \(k=3\) extension appears only after the main results above.

**Block 7 — Train Stage 1 (1-Rectified Flow / Standard CFM)**

This is the baseline training stage. We learn a velocity field on MNIST using the standard conditional flow matching objective before applying any rectification.
"""

# Block 7: Train stage 1 (1-Rectified Flow / standard CFM stage)

stage1_ckpt_dir = OUT_DIR / "stage1_checkpoints"

stage1_model, stage1_losses, stage1_history = train_cfm_stage(
    model=teacher,
    loader=train_loader,
    device=device,
    epochs=CFM_EPOCHS,
    lr=LR,
    stage_name="stage1_cfm",
    track_metrics=TRACK_METRICS,
    track_metric_every=TRACK_METRIC_EVERY,
    track_straightness_batches=TRACK_STRAIGHTNESS_BATCHES,
    track_endpoint_batches=TRACK_ENDPOINT_BATCHES,
    track_endpoint_steps=TRACK_ENDPOINT_STEPS,
    checkpoint_dir=stage1_ckpt_dir if SAVE_EPOCH_CHECKPOINTS else None,
)

torch.save(
    {"model": stage1_model.state_dict(), "losses": stage1_losses, "history": stage1_history},
    OUT_DIR / "stage1_cfm.pt",
)
with open(OUT_DIR / "stage1_history.json", "w", encoding="utf-8") as f:
    json.dump(stage1_history, f, indent=2)

print("Saved:", OUT_DIR / "stage1_cfm.pt")
print("Saved:", OUT_DIR / "stage1_history.json")

"""**Block 8 — Train Stage 2 (2-Rectified Flow via Reflow)**

This cell performs the main algorithmic step from the paper: reflow. It generates endpoint pairs using the trained stage-1 model and then trains a new model on those pairs, which should produce a straighter flow.
"""

# Block 9: Train stage 2 (2-Rectified Flow via reflow)

stage2_ckpt_dir = OUT_DIR / "stage2_checkpoints"

stage2_model, stage2_losses, stage2_history = train_reflow_stage(
    teacher=stage1_model,
    loader=train_loader,
    device=device,
    epochs=REFLOW_EPOCHS,
    lr=LR,
    stage_name="stage2_reflow",
    pair_steps=PAIR_STEPS,
    pair_solver=PAIR_SOLVER,
    track_metrics=TRACK_METRICS,
    track_metric_every=TRACK_METRIC_EVERY,
    track_straightness_batches=TRACK_STRAIGHTNESS_BATCHES,
    track_endpoint_batches=TRACK_ENDPOINT_BATCHES,
    track_endpoint_steps=TRACK_ENDPOINT_STEPS,
    checkpoint_dir=stage2_ckpt_dir if SAVE_EPOCH_CHECKPOINTS else None,
)

torch.save(
    {"model": stage2_model.state_dict(), "losses": stage2_losses, "history": stage2_history},
    OUT_DIR / "stage2_reflow.pt",
)
with open(OUT_DIR / "stage2_history.json", "w", encoding="utf-8") as f:
    json.dump(stage2_history, f, indent=2)

print("Saved:", OUT_DIR / "stage2_reflow.pt")
print("Saved:", OUT_DIR / "stage2_history.json")

"""**Block 9 — Main Qualitative Experiment: Sample Grids Across NFEs**

This cell generates unconditional MNIST samples for several numbers of function evaluations (NFEs), such as 1, 2, 4, 8, and 16. These grids provide the main visual comparison between the baseline flow and the rectified flow.
"""

# Block 11: Main qualitative experiment
# Compare stage 1 vs stage 2 at NFE = 1, 2, 4, 8, 16

main_stage_models = {
    "stage1_cfm": stage1_model.eval(),
    "stage2_reflow": stage2_model.eval(),
}

for stage_name, model in main_stage_models.items():
    stage_dir = OUT_DIR / stage_name
    stage_dir.mkdir(parents=True, exist_ok=True)
    for steps in SAMPLE_STEPS:
        samples = sample_images(
            model=model,
            n_samples=VIS_N,
            batch_size=VIS_N,
            num_steps=steps,
            device=device,
            solver=SAMPLE_SOLVER,
        )
        save_sample_grid(
            samples,
            stage_dir / f"samples_{steps:02d}_steps.png",
            show_inline=SHOW_SAVED_SAMPLE_GRIDS and (steps in INLINE_SAMPLE_STEPS),
            title=f"{stage_name} | NFE={steps}",
        )

"""**Block 12 — Main Quantitative Comparison for Stage 1 vs Stage 2**

This cell evaluates both models with the three flow-side metrics and stores the results in a compact dictionary:

- paper-style **straightness**,
- **endpoint-consistency**,
- **quadratic transport cost**.
"""

# Block 12: Main quantitative table for stage 1 vs stage 2

main_results = {}
for stage_name, model in main_stage_models.items():
    main_results[stage_name] = {
        "paper_straightness": estimate_paper_straightness(
            model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            pair_steps=PAIR_STEPS,
            pair_solver=PAIR_SOLVER,
            batches=FINAL_METRIC_BATCHES,
        ),
        "endpoint_consistency": estimate_endpoint_consistency(
            model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            num_steps=max(SAMPLE_STEPS),
            solver=SAMPLE_SOLVER,
            batches=max(2, FINAL_METRIC_BATCHES // 2),
        ),
        "quadratic_transport_cost": estimate_quadratic_transport_cost(
            model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            pair_steps=PAIR_STEPS,
            pair_solver=PAIR_SOLVER,
            batches=FINAL_METRIC_BATCHES,
        ),
    }

print(json.dumps(main_results, indent=2))

with open(OUT_DIR / "main_metrics_stage1_stage2.json", "w", encoding="utf-8") as f:
    json.dump(main_results, f, indent=2)

print("Saved:", OUT_DIR / "main_metrics_stage1_stage2.json")

"""**Block 13 — Compact Metric Plots for Stage 1 vs Stage 2**

This cell plots the final values of the three main flow-side diagnostics across the two main stages:

- paper-style **straightness**,
- **endpoint-consistency**,
- **quadratic transport cost**.

These plots are meant to support the same story as the sample grids: stage 2 should ideally be straighter, have better local-to-endpoint alignment, and not increase the chosen quadratic transport cost.

"""

# Block 13: Compact metric plots for stage 1 vs stage 2

stage_names = list(main_results.keys())
straightness_vals = [main_results[s]["paper_straightness"] for s in stage_names]
endpoint_vals = [main_results[s]["endpoint_consistency"] for s in stage_names]
transport_vals = [main_results[s]["quadratic_transport_cost"] for s in stage_names]

# Paper straightness
plt.figure(figsize=(6, 4))
bars = plt.bar(stage_names, straightness_vals)
plt.title("Straightness")
plt.ylabel("Lower is better")
plt.xticks(rotation=15)
for b, v in zip(bars, straightness_vals):
    plt.text(b.get_x() + b.get_width()/2, v, f"{v:.4f}", ha="center", va="bottom")
plt.tight_layout()
plt.show()

# Endpoint-consistency
plt.figure(figsize=(6, 4))
bars = plt.bar(stage_names, endpoint_vals)
plt.title("Endpoint-consistency")
plt.ylabel("Lower is better")
plt.xticks(rotation=15)
for b, v in zip(bars, endpoint_vals):
    plt.text(b.get_x() + b.get_width()/2, v, f"{v:.4f}", ha="center", va="bottom")
plt.tight_layout()
plt.show()

# Quadratic transport cost
plt.figure(figsize=(6, 4))
bars = plt.bar(stage_names, transport_vals)
plt.title("Quadratic transport cost")
plt.ylabel("Lower is better")
plt.xticks(rotation=15)

ymin = min(transport_vals) - 5
ymax = max(transport_vals) + 5
plt.ylim(ymin, ymax)

for b, v in zip(bars, transport_vals):
    plt.text(b.get_x() + b.get_width()/2, v, f"{v:.2f}", ha="center", va="bottom")

plt.tight_layout()
plt.show()

"""## **Checkpoint Metric Curves**

These are the progress plots that matter most for this notebook: how the paper-style **straightness**, the extra **endpoint-consistency**, and the **quadratic transport cost** evolve during training.

**Block 14 — Checkpoint Metric Histories**

This cell prints the metric history recorded during training for stage 1 and stage 2. These histories are useful for checking whether rectification is improving the desired geometry progressively over epochs.
"""

# Block 14: View the epoch-wise metric histories for stage 1 and stage 2

print("Stage 1 history:")
print(json.dumps(stage1_history, indent=2))

print("\nStage 2 history:")
print(json.dumps(stage2_history, indent=2))

"""**Block 15 — Plot Metrics vs Epoch / Checkpoint**

This cell turns the recorded histories into curves over training time. It overlays the raw tracked points with a light moving-average smoother so the plots are easier to read without changing the underlying saved metrics.
"""

# Block 15: Plot metric histories vs checkpoint/epoch

def smooth_history(values, window: int):
    if window <= 1 or len(values) <= 2:
        return np.asarray(values, dtype=float)
    smoothed = []
    for i in range(len(values)):
        lo = max(0, i - window + 1)
        smoothed.append(float(np.mean(values[lo : i + 1])))
    return np.asarray(smoothed, dtype=float)


def plot_metric_history(history, metric_key: str, stage_name: str, title: str):
    xs = [entry["epoch"] for entry in history if metric_key in entry]
    ys = [entry[metric_key] for entry in history if metric_key in entry]
    if len(xs) == 0:
        print(f"No tracked values found for {stage_name} / {metric_key}.")
        return

    raw = np.asarray(ys, dtype=float)
    smooth = smooth_history(raw, HISTORY_SMOOTHING_WINDOW)

    plt.figure(figsize=(6, 4))
    plt.plot(xs, raw, marker="o", alpha=0.25, linewidth=1.0, label="raw")
    plt.plot(xs, smooth, marker="o", linewidth=2.0, label="smoothed")
    plt.title(title)
    plt.xlabel("Epoch / checkpoint")
    plt.ylabel("Lower is better")
    plt.grid(True, alpha=0.3)
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.show()

plot_metric_history(
    stage1_history,
    metric_key="paper_straightness",
    stage_name="stage1_cfm",
    title="Paper straightness",
)

plot_metric_history(
    stage1_history,
    metric_key="endpoint_consistency",
    stage_name="stage1_cfm",
    title="Endpoint-consistency",
)

plot_metric_history(
    stage1_history,
    metric_key="quadratic_transport_cost",
    stage_name="stage1_cfm",
    title="Quadratic transport cost",
)

plot_metric_history(
    stage2_history,
    metric_key="paper_straightness",
    stage_name="stage2_reflow",
    title="Paper straightness",
)

plot_metric_history(
    stage2_history,
    metric_key="endpoint_consistency",
    stage_name="stage2_reflow",
    title="Endpoint-consistency",
)

plot_metric_history(
    stage2_history,
    metric_key="quadratic_transport_cost",
    stage_name="stage2_reflow",
    title="Quadratic transport cost",
)

"""**Block 15A — Save Checkpoint Metric Histories**

This cell saves the tracked metric histories to disk so they can be reused later without rerunning the full notebook. This is helpful for reporting or for making external plots.
"""

# Block 15A: Save the checkpoint metric histories together

checkpoint_metric_histories = {
    "stage1_cfm": stage1_history,
    "stage2_reflow": stage2_history,
}

with open(OUT_DIR / "checkpoint_metric_histories.json", "w", encoding="utf-8") as f:
    json.dump(checkpoint_metric_histories, f, indent=2)

print("Saved:", OUT_DIR / "checkpoint_metric_histories.json")

"""## **Main One-Step Distillation after $k=2$**

This section adds the paper’s **final one-step distillation stage** after the **2-Rectified Flow**.

The source flow here is the trained **stage-2 reflow model**.  
We generate pairs
\[
(Z_0^2, Z_1^2)
\]
by sampling noise \(Z_0^2\) and integrating the stage-2 flow to obtain \(Z_1^2\). Then we train a direct predictor
\[
\hat T_2(z_0)=z_0+v_	heta(z_0,0)
\]
to match the endpoint in **one step**.

For this part:
- the **source flow’s straightness** tells us whether one-step approximation should be easy,
- the distilled model is evaluated with **one-step endpoint MSE**.

**Block 16 — Train One-Step Distillation after $k=2$**

We now distill the **2-Rectified Flow** into a one-step predictor. This is separate from reflow: it does **not** learn a new coupling or a new time-dependent flow. It simply learns to jump from the initial noise directly to the final endpoint of the already-rectified teacher flow.
"""

# Block 16: Train one-step distillation after k=2

stage2_distill_ckpt_dir = OUT_DIR / "stage2_distill_checkpoints"

stage2_distill_model, stage2_distill_losses, stage2_distill_history = train_distillation_stage(
    source_flow=stage2_model,
    loader=train_loader,
    device=device,
    epochs=DISTILL_EPOCHS,
    lr=LR,
    stage_name="stage2_distill",
    pair_steps=PAIR_STEPS,
    pair_solver=PAIR_SOLVER,
    track_metrics=TRACK_METRICS,
    track_metric_every=TRACK_METRIC_EVERY,
    checkpoint_dir=stage2_distill_ckpt_dir if SAVE_EPOCH_CHECKPOINTS else None,
)

torch.save(
    {"model": stage2_distill_model.state_dict(), "losses": stage2_distill_losses, "history": stage2_distill_history},
    OUT_DIR / "stage2_distill.pt",
)
with open(OUT_DIR / "stage2_distill_history.json", "w", encoding="utf-8") as f:
    json.dump(stage2_distill_history, f, indent=2)

print("Saved:", OUT_DIR / "stage2_distill.pt")
print("Saved:", OUT_DIR / "stage2_distill_history.json")

"""**Block 16A — One-Step Samples after $k=2$ Distillation**

This block saves a **one-step sample grid** from the distilled model. At inference time, this model does not integrate the ODE. It directly applies the learned map
\[
z_0 \mapsto \hat T_2(z_0).
\]

"""

# Block 16: One-step samples after k=2 distillation

stage2_distill_dir = OUT_DIR / "stage2_distill"
stage2_distill_dir.mkdir(parents=True, exist_ok=True)

stage2_distill_samples = sample_images_one_step(
    model=stage2_distill_model,
    n_samples=VIS_N,
    batch_size=VIS_N,
    device=device,
)
save_sample_grid(
    stage2_distill_samples,
    stage2_distill_dir / "samples_01_step.png",
    show_inline=SHOW_SAVED_SAMPLE_GRIDS,
    title="stage2_distill | one step",
)
print("Saved:", stage2_distill_dir / "samples_01_step.png")

"""**Block 16C — Distillation Metrics after $k=2$**

For the source **2-Rectified Flow**, we keep reporting:

- the paper-style **straightness measure**,
- the earlier **endpoint-consistency** metric,
- the special **\(t=0\) endpoint-consistency**, which is exactly the one-step extrapolation error of the flow itself,
- and the **quadratic transport cost** \( \mathbb{E}\|Z_1-Z_0\|^2 \), included as a special-case transport-cost diagnostic.

For the distilled one-step model, the main metric is:
\[
\mathbb{E}\big[\|Z_1^2-\hat T_2(Z_0^2)\|^2\big],
\]
which we call **one-step endpoint MSE**.

So rectification is still the part that improves **straightness**, while distillation uses that straightness to make **one-step inference** work better.

These values are now computed with larger Monte Carlo batches than the training-time checkpoints so the final comparison is more stable.
"""

# Block 16C: Distillation metrics after k=2

stage2_distill_results = {
    "stage2_reflow_source_flow": {
        "paper_straightness": estimate_paper_straightness(
            stage2_model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            pair_steps=PAIR_STEPS,
            pair_solver=PAIR_SOLVER,
            batches=FINAL_METRIC_BATCHES,
        ),
        "endpoint_consistency": estimate_endpoint_consistency(
            stage2_model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            num_steps=max(SAMPLE_STEPS),
            solver=SAMPLE_SOLVER,
            batches=max(2, FINAL_METRIC_BATCHES // 2),
        ),
        "endpoint_consistency_t0": estimate_t0_endpoint_consistency(
            stage2_model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            pair_steps=PAIR_STEPS,
            pair_solver=PAIR_SOLVER,
            batches=FINAL_METRIC_BATCHES,
        ),
        "quadratic_transport_cost": estimate_quadratic_transport_cost(
            stage2_model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            pair_steps=PAIR_STEPS,
            pair_solver=PAIR_SOLVER,
            batches=FINAL_METRIC_BATCHES,
        ),
    },
    "stage2_distilled_one_step": {
        "one_step_endpoint_mse": estimate_distilled_one_step_mse(
            distilled_model=stage2_distill_model,
            source_flow=stage2_model,
            device=device,
            batch_size=EVAL_BATCH_SIZE,
            pair_steps=PAIR_STEPS,
            pair_solver=PAIR_SOLVER,
            batches=FINAL_METRIC_BATCHES,
        ),
    },
}

print(json.dumps(stage2_distill_results, indent=2))

with open(OUT_DIR / "stage2_distill_metrics.json", "w", encoding="utf-8") as f:
    json.dump(stage2_distill_results, f, indent=2)

print("Saved:", OUT_DIR / "stage2_distill_metrics.json")

"""**Block 16D — Distillation Plots and Summary for $k=2$**

This cell keeps the core distillation curve and prints the final summary dictionary. The source-flow transport cost remains available in the saved metrics dictionary, but it is no longer mixed into a shared bar chart with the smaller error metrics.

"""

# Block 16D: Distillation plots for k=2

plot_metric_history(
    stage2_distill_history,
    metric_key="one_step_endpoint_mse",
    stage_name="stage2_distill",
    title="One-step endpoint MSE",
)

print(json.dumps(stage2_distill_results, indent=2))

with open(OUT_DIR / "stage2_distill_metrics_pretty.json", "w", encoding="utf-8") as f:
    json.dump(stage2_distill_results, f, indent=2)

print("Saved:", OUT_DIR / "stage2_distill_metrics_pretty.json")

"""## **Optional Extension: Stage 3**

Everything in this section is optional and comes **after** the priority experiments above. If enabled, we repeat the same concise set of plots for the 3-rectified model.

**Block 16 — Optional Stage 3 Training ($k=3$)**

Everything from this point onward is optional. If enabled, this cell trains one more rectified model using stage 2 as the teacher, giving a simple demonstration of a third rectification step.
"""

# Block 16: Optional stage 3 training

if RUN_OPTIONAL_K3:
    stage3_ckpt_dir = OUT_DIR / "stage3_checkpoints"

    stage3_model, stage3_losses, stage3_history = train_reflow_stage(
        teacher=stage2_model,
        loader=train_loader,
        device=device,
        epochs=REFLOW_EPOCHS,
        lr=LR,
        stage_name="stage3_reflow",
        pair_steps=PAIR_STEPS,
        pair_solver=PAIR_SOLVER,
        track_metrics=TRACK_METRICS,
        track_metric_every=TRACK_METRIC_EVERY,
        track_straightness_batches=TRACK_STRAIGHTNESS_BATCHES,
        track_endpoint_batches=TRACK_ENDPOINT_BATCHES,
        track_endpoint_steps=TRACK_ENDPOINT_STEPS,
        checkpoint_dir=stage3_ckpt_dir if SAVE_EPOCH_CHECKPOINTS else None,
    )

    torch.save(
        {"model": stage3_model.state_dict(), "losses": stage3_losses, "history": stage3_history},
        OUT_DIR / "stage3_reflow.pt",
    )
    with open(OUT_DIR / "stage3_history.json", "w", encoding="utf-8") as f:
        json.dump(stage3_history, f, indent=2)

    print("Saved:", OUT_DIR / "stage3_reflow.pt")
    print("Saved:", OUT_DIR / "stage3_history.json")
else:
    stage3_model, stage3_losses, stage3_history = None, [], []
    print("RUN_OPTIONAL_K3 is False, so stage 3 is skipped.")

"""**Block 18 — Optional Qualitative Comparison Including Stage 3**

If stage 3 is enabled, this cell extends the NFE sample-grid comparison to include the 3-rectified model. This is useful for checking whether an additional rectification step gives any visible benefit on MNIST.
"""

# Block 18: Optional qualitative comparison including stage 3

if RUN_OPTIONAL_K3 and stage3_model is not None:
    stage3_models = {
        "stage1_cfm": stage1_model.eval(),
        "stage2_reflow": stage2_model.eval(),
        "stage3_reflow": stage3_model.eval(),
    }

    for stage_name, model in stage3_models.items():
        stage_dir = OUT_DIR / stage_name
        stage_dir.mkdir(parents=True, exist_ok=True)
        for steps in SAMPLE_STEPS:
            samples = sample_images(
                model=model,
                n_samples=VIS_N,
                batch_size=VIS_N,
                num_steps=steps,
                device=device,
                solver=SAMPLE_SOLVER,
            )
            save_sample_grid(
                samples,
                stage_dir / f"samples_{steps:02d}_steps_k3_run.png",
                show_inline=SHOW_SAVED_SAMPLE_GRIDS and (steps in INLINE_SAMPLE_STEPS),
                title=f"{stage_name} | NFE={steps}",
            )

"""**Block 19 — Optional Quantitative Comparison Including Stage 3**

This cell computes the same three flow-side metrics for the stage-3 model and compares them against stages 1 and 2. It mirrors the earlier quantitative block but now includes the optional extension.

"""

# Block 19: Optional quantitative comparison including stage 3

if RUN_OPTIONAL_K3 and stage3_model is not None:
    k3_results = {}
    stage3_models = {
        "stage1_cfm": stage1_model.eval(),
        "stage2_reflow": stage2_model.eval(),
        "stage3_reflow": stage3_model.eval(),
    }

    for stage_name, model in stage3_models.items():
        k3_results[stage_name] = {
            "paper_straightness": estimate_paper_straightness(
                model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=FINAL_METRIC_BATCHES,
            ),
            "endpoint_consistency": estimate_endpoint_consistency(
                model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                num_steps=max(SAMPLE_STEPS),
                solver=SAMPLE_SOLVER,
                batches=max(2, FINAL_METRIC_BATCHES // 2),
            ),
            "quadratic_transport_cost": estimate_quadratic_transport_cost(
                model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=FINAL_METRIC_BATCHES,
            ),
        }

    print(json.dumps(k3_results, indent=2))

    with open(OUT_DIR / "optional_k3_metrics.json", "w", encoding="utf-8") as f:
        json.dump(k3_results, f, indent=2)

    print("Saved:", OUT_DIR / "optional_k3_metrics.json")

"""**Block 19A — Optional Metric Plots Including Stage 3**

If stage 3 is enabled, this cell plots the final values of the same three flow-side metrics across all three stages. This helps show whether the optional extra rectification step continues the same trend.

"""

# Block 19A: Optional compact metric plots including stage 3

if RUN_OPTIONAL_K3 and stage3_model is not None:
    stage_names = list(k3_results.keys())
    straightness_vals = [k3_results[s]["paper_straightness"] for s in stage_names]
    endpoint_vals = [k3_results[s]["endpoint_consistency"] for s in stage_names]
    transport_vals = [k3_results[s]["quadratic_transport_cost"] for s in stage_names]

    # Paper straightness
    plt.figure(figsize=(6, 4))
    bars = plt.bar(stage_names, straightness_vals)
    plt.title("Straightness")
    plt.ylabel("Lower is better")
    plt.xticks(rotation=15)
    for b, v in zip(bars, straightness_vals):
        plt.text(b.get_x() + b.get_width() / 2, v, f"{v:.4f}", ha="center", va="bottom")
    plt.tight_layout()
    plt.show()

    # Endpoint-consistency
    plt.figure(figsize=(6, 4))
    bars = plt.bar(stage_names, endpoint_vals)
    plt.title("Endpoint-consistency")
    plt.ylabel("Lower is better")
    plt.xticks(rotation=15)
    for b, v in zip(bars, endpoint_vals):
        plt.text(b.get_x() + b.get_width() / 2, v, f"{v:.4f}", ha="center", va="bottom")
    plt.tight_layout()
    plt.show()

    # Quadratic transport cost
    plt.figure(figsize=(6, 4))
    bars = plt.bar(stage_names, transport_vals)
    plt.title("Quadratic transport cost")
    plt.ylabel("Lower is better")
    plt.xticks(rotation=15)

    ymin = min(transport_vals) - 5
    ymax = max(transport_vals) + 5
    plt.ylim(ymin, ymax)

    for b, v in zip(bars, transport_vals):
        plt.text(b.get_x() + b.get_width() / 2, v, f"{v:.2f}", ha="center", va="bottom")

    plt.tight_layout()
    plt.show()
else:
    print("Skipping optional stage-3 metric plots because RUN_OPTIONAL_K3=False.")

"""**Block 19B — Optional Stage-3 Metric Curves**

This cell plots the checkpoint-wise straightness and endpoint-consistency curves for stage 3. It is the optional analogue of the main training-progress plots above.
"""

# Block 19B: Optional checkpoint-metric plots for stage 3

if RUN_OPTIONAL_K3 and stage3_model is not None:
    plot_metric_history(
        stage3_history,
        metric_key="paper_straightness",
        stage_name="stage3_reflow",
        title="Paper straightness",
    )

    plot_metric_history(
        stage3_history,
        metric_key="endpoint_consistency",
        stage_name="stage3_reflow",
        title="Endpoint-consistency",
    )

    plot_metric_history(
        stage3_history,
        metric_key="quadratic_transport_cost",
        stage_name="stage3_reflow",
        title="Quadratic transport cost",
    )
else:
    print("Skipping optional stage-3 checkpoint curves because RUN_OPTIONAL_K3=False.")

"""## **Optional One-Step Distillation after $k=3$**

If you run the optional **3-Rectified Flow**, you can also apply the same final one-step distillation idea there.

The logic is the same as for \(k=2\):
- first obtain a straighter source flow by rectification,
- then distill its endpoint coupling into a direct one-step predictor.

**Block 22A — Optional Train One-Step Distillation after $k=3$**

This block is only active when the optional stage-3 reflow is enabled.
"""

# Block 22A: Optional train one-step distillation after k=3

if RUN_OPTIONAL_K3 and stage3_model is not None:
    stage3_distill_ckpt_dir = OUT_DIR / "stage3_distill_checkpoints"

    stage3_distill_model, stage3_distill_losses, stage3_distill_history = train_distillation_stage(
        source_flow=stage3_model,
        loader=train_loader,
        device=device,
        epochs=DISTILL_EPOCHS,
        lr=LR,
        stage_name="stage3_distill",
        pair_steps=PAIR_STEPS,
        pair_solver=PAIR_SOLVER,
        track_metrics=TRACK_METRICS,
        track_metric_every=TRACK_METRIC_EVERY,
        checkpoint_dir=stage3_distill_ckpt_dir if SAVE_EPOCH_CHECKPOINTS else None,
    )

    torch.save(
        {"model": stage3_distill_model.state_dict(), "losses": stage3_distill_losses, "history": stage3_distill_history},
        OUT_DIR / "stage3_distill.pt",
    )
    with open(OUT_DIR / "stage3_distill_history.json", "w", encoding="utf-8") as f:
        json.dump(stage3_distill_history, f, indent=2)

    print("Saved:", OUT_DIR / "stage3_distill.pt")
    print("Saved:", OUT_DIR / "stage3_distill_history.json")
else:
    stage3_distill_model, stage3_distill_losses, stage3_distill_history = None, [], []
    print("RUN_OPTIONAL_K3 is False, so optional k=3 distillation is skipped.")

"""**Block 22B — Optional One-Step Samples after $k=3$ Distillation**

If stage 3 is enabled, this saves a one-step sample grid from the distilled \(k=3\) predictor.

"""

# Block 22B: Optional one-step samples after k=3 distillation

if RUN_OPTIONAL_K3 and stage3_distill_model is not None:
    stage3_distill_dir = OUT_DIR / "stage3_distill"
    stage3_distill_dir.mkdir(parents=True, exist_ok=True)

    stage3_distill_samples = sample_images_one_step(
        model=stage3_distill_model,
        n_samples=VIS_N,
        batch_size=VIS_N,
        device=device,
    )
    save_sample_grid(
        stage3_distill_samples,
        stage3_distill_dir / "samples_01_step.png",
        show_inline=SHOW_SAVED_SAMPLE_GRIDS,
        title="stage3_distill | one step",
    )
    print("Saved:", stage3_distill_dir / "samples_01_step.png")
else:
    print("Skipping optional k=3 one-step sample grid.")

"""**Block 22C — Optional Distillation Metrics after $k=3$**

As before, the source flow keeps the **straightness** interpretation and also carries the **quadratic transport cost** diagnostic, while the distilled model is evaluated by **one-step endpoint MSE**.

As above, the final numbers here use larger Monte Carlo batches than the checkpoint curves.
"""

# Block 22C: Optional distillation metrics after k=3

if RUN_OPTIONAL_K3 and stage3_model is not None and stage3_distill_model is not None:
    stage3_distill_results = {
        "stage3_reflow_source_flow": {
            "paper_straightness": estimate_paper_straightness(
                stage3_model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=FINAL_METRIC_BATCHES,
            ),
            "endpoint_consistency": estimate_endpoint_consistency(
                stage3_model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                num_steps=max(SAMPLE_STEPS),
                solver=SAMPLE_SOLVER,
                batches=max(2, FINAL_METRIC_BATCHES // 2),
            ),
            "endpoint_consistency_t0": estimate_t0_endpoint_consistency(
                stage3_model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=FINAL_METRIC_BATCHES,
            ),
            "quadratic_transport_cost": estimate_quadratic_transport_cost(
                stage3_model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=FINAL_METRIC_BATCHES,
            ),
        },
        "stage3_distilled_one_step": {
            "one_step_endpoint_mse": estimate_distilled_one_step_mse(
                distilled_model=stage3_distill_model,
                source_flow=stage3_model,
                device=device,
                batch_size=EVAL_BATCH_SIZE,
                pair_steps=PAIR_STEPS,
                pair_solver=PAIR_SOLVER,
                batches=FINAL_METRIC_BATCHES,
            ),
        },
    }

    print(json.dumps(stage3_distill_results, indent=2))

    with open(OUT_DIR / "stage3_distill_metrics.json", "w", encoding="utf-8") as f:
        json.dump(stage3_distill_results, f, indent=2)

    print("Saved:", OUT_DIR / "stage3_distill_metrics.json")
else:
    stage3_distill_results = {}
    print("Skipping optional k=3 distillation metrics.")

"""**Block 22D — Optional Distillation Plots and Summary for $k=3$**

This cell keeps the core one-step endpoint-MSE curve for the optional $k=3$ distillation stage and prints the final summary dictionary instead of mixing different scales in one bar chart.

"""

# Block 22D: Optional distillation plots for k=3

if RUN_OPTIONAL_K3 and stage3_distill_model is not None:
    plot_metric_history(
        stage3_distill_history,
        metric_key="one_step_endpoint_mse",
        stage_name="stage3_distill",
        title="One-step endpoint MSE",
    )

    print(json.dumps(stage3_distill_results, indent=2))

    with open(OUT_DIR / "stage3_distill_metrics_pretty.json", "w", encoding="utf-8") as f:
        json.dump(stage3_distill_results, f, indent=2)

    print("Saved:", OUT_DIR / "stage3_distill_metrics_pretty.json")
else:
    print("Skipping optional k=3 distillation plots.")

"""**Block 23 — Final Save Bundle**

This final cell packages the main results, histories, and configuration into files saved under the output directory. It gives you one compact place to look for all final artifacts from the run.
"""

# Block 23: save

summary_bundle = {
    "stage1_losses": stage1_losses,
    "stage2_losses": stage2_losses,
    "stage1_history": stage1_history,
    "stage2_history": stage2_history,
    "main_results": main_results,
    "stage2_distill_losses": stage2_distill_losses,
    "stage2_distill_history": stage2_distill_history,
    "stage2_distill_results": stage2_distill_results,
    "config": {
        "seed": SEED,
        "batch_size": BATCH_SIZE,
        "hidden_dim": HIDDEN_DIM,
        "n_layers": N_LAYERS,
        "lr": LR,
        "cfm_epochs": CFM_EPOCHS,
        "reflow_epochs": REFLOW_EPOCHS,
        "distill_epochs": DISTILL_EPOCHS,
        "pair_steps": PAIR_STEPS,
        "pair_solver": PAIR_SOLVER,
        "sample_solver": SAMPLE_SOLVER,
        "sample_steps": SAMPLE_STEPS,
        "track_metrics": TRACK_METRICS,
        "track_metric_every": TRACK_METRIC_EVERY,
        "track_straightness_batches": TRACK_STRAIGHTNESS_BATCHES,
        "track_endpoint_steps": TRACK_ENDPOINT_STEPS,
    },
}

if RUN_OPTIONAL_K3 and stage3_model is not None:
    summary_bundle["stage3_losses"] = stage3_losses
    summary_bundle["stage3_history"] = stage3_history

if RUN_OPTIONAL_K3 and stage3_distill_model is not None:
    summary_bundle["stage3_distill_losses"] = stage3_distill_losses
    summary_bundle["stage3_distill_history"] = stage3_distill_history
    summary_bundle["stage3_distill_results"] = stage3_distill_results

torch.save(summary_bundle, OUT_DIR / "notebook_summary.pt")

print("All outputs saved under:", OUT_DIR.resolve())

# Copy the current notebook run logs/results to Google Drive

from google.colab import drive
from pathlib import Path
from datetime import datetime
import shutil
import os

#Mount Google Drive
drive.mount('/content/drive')

#Set source and destination
SRC_DIR = Path("mnist_rectified_flow_notebook_runs")  # current local run folder
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
DST_ROOT = Path("/content/drive/MyDrive/mnist_rectified_flow_notebook_runs_backups")
DST_DIR = DST_ROOT / f"run_{timestamp}"

#Validate source
if not SRC_DIR.exists():
    raise FileNotFoundError(f"Source folder not found: {SRC_DIR.resolve()}")

#Create destination and copy everything
DST_ROOT.mkdir(parents=True, exist_ok=True)
shutil.copytree(SRC_DIR, DST_DIR)

#also create a latest snapshot
LATEST_DIR = DST_ROOT / "latest"
if LATEST_DIR.exists():
    shutil.rmtree(LATEST_DIR)
shutil.copytree(SRC_DIR, LATEST_DIR)

#Print summary
all_files = [p for p in DST_DIR.rglob("*") if p.is_file()]
total_bytes = sum(p.stat().st_size for p in all_files)

print(f"Copied logs to: {DST_DIR}")
print(f"Updated latest snapshot: {LATEST_DIR}")
print(f"Total files copied: {len(all_files)}")
print(f"Total size: {total_bytes / (1024**2):.2f} MB")